### ISSUE TITLE
describe is not a function while running test 

### ISSUE THREAD

**Issue by Nikunj-bisht** [MarufHasan24/mathlib#11]
TypeError: describe is not a function
 ❯ test/vector.test.js:4:1
      2| const { describe, it, expect } = require("vitest");
      3| 
      4| describe("Vector", function () {
       | ^
      5|     it("should add vectors", function () {
      6|         expect(vector1.add(vector2)).toEqual(

**Comment by MarufHasan24** [comment]
It was resolved yesterday!
