### ISSUE TITLE
[Feature]:Make Footer more attractive by adding social media's logo's and links 

### ISSUE THREAD

**Issue by parthksingh1** [MarufHasan24/mathlib#6]
Make footer more attractive by adding social media handels logo and links which will make footer more atrractive

**Comment by parthksingh1** [comment]
Please assign me this will make footer more attractive

**Comment by MarufHasan24** [comment]
@parthksingh1 I'm not concern about footer. mathlib is a JavaScript library, it's not a ui/ux desige site!

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by MarufHasan24** [comment]
@saku1331 you wanted to work on what?

**Comment by Clou-D-Walker** [comment]
I would like to create the footer attractive and responsive.

**Comment by Clou-D-Walker** [comment]
I want to work on mathlib js library and solve mathematical prblms.
