### ISSUE TITLE
Adding a new feature

### ISSUE THREAD

**Issue by payallenka** [MarufHasan24/mathlib#7]
I would like to contribute by building the inverse trigonometry feature. Kindly assign me this task, I am searching for repos to contribute for the Hactoberfest 2023.

**Comment by MarufHasan24** [comment]
@payallenka Yah, sure! clone my branch and write your code. Then hold your pull request for October 1. Here a todo list for you: [To-Do list](https://github.com/MarufHasan24/mathlib/discussions/5). you can pick a subject from here.
