### ISSUE TITLE
Convert list items to checkboxes in todo list

### ISSUE THREAD

**Issue by Rishab49** [MarufHasan24/mathlib#9]
I am planning to work on some of the tasks on to-do list, and I think it would be helpful to convert the to-do list items to checkboxes. This will make it clear to other developers who want to contribute which tasks are completed and which are not.

**Comment by MarufHasan24** [comment]
@Rishab49 if you willing to to some stuff in mathlib library, then you are welcomed. Todo list is in discussion section. As you know, according to the hacktoberfest rule, that will not counted as hacktoberfest23 PR. If you want, you can.
